// <auto-generated />
using System;
using CaioMatheusDev.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaioMatheusDev.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260716203106_AddBackendRoomCommunity")]
    partial class AddBackendRoomCommunity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("auth_users", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomCommunityPostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("backend_room_community_posts", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomDrawingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("backend_room_drawings", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomNoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("backend_room_notes", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.PasswordResetTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomCommunityPostEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", "User")
                        .WithMany("BackendRoomCommunityPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomDrawingEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", "User")
                        .WithOne("BackendRoomDrawing")
                        .HasForeignKey("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomDrawingEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomNoteEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", "User")
                        .WithMany("BackendRoomNotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.PasswordResetTokenEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", b =>
                {
                    b.Navigation("BackendRoomCommunityPosts");

                    b.Navigation("BackendRoomDrawing");

                    b.Navigation("BackendRoomNotes");

                    b.Navigation("PasswordResetTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
