// <auto-generated />
using System;
using CaioMatheusDev.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaioMatheusDev.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260721152613_AddWalletLab")]
    partial class AddWalletLab
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("auth_users", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomCommunityPostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("backend_room_community_posts", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomCommunityPostLikeEntity", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("backend_room_community_post_likes", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomDrawingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("backend_room_drawings", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomNoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("backend_room_notes", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.PasswordResetTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletMovementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransferId");

                    b.HasIndex("WalletId", "CreatedAt");

                    b.ToTable("wallet_movements", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletTransferEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("FromWalletId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ToWalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FromWalletId");

                    b.HasIndex("ToWalletId");

                    b.ToTable("wallet_transfers", (string)null);
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomCommunityPostEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", "User")
                        .WithMany("BackendRoomCommunityPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomCommunityPostLikeEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomCommunityPostEntity", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", "User")
                        .WithMany("BackendRoomCommunityPostLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomDrawingEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", "User")
                        .WithOne("BackendRoomDrawing")
                        .HasForeignKey("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomDrawingEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomNoteEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", "User")
                        .WithMany("BackendRoomNotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.PasswordResetTokenEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletMovementEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletTransferEntity", "Transfer")
                        .WithMany("Movements")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletEntity", "Wallet")
                        .WithMany("Movements")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transfer");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletTransferEntity", b =>
                {
                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletEntity", "FromWallet")
                        .WithMany("OutgoingTransfers")
                        .HasForeignKey("FromWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletEntity", "ToWallet")
                        .WithMany("IncomingTransfers")
                        .HasForeignKey("ToWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromWallet");

                    b.Navigation("ToWallet");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.AuthUserEntity", b =>
                {
                    b.Navigation("BackendRoomCommunityPostLikes");

                    b.Navigation("BackendRoomCommunityPosts");

                    b.Navigation("BackendRoomDrawing");

                    b.Navigation("BackendRoomNotes");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.BackendRoomCommunityPostEntity", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletEntity", b =>
                {
                    b.Navigation("IncomingTransfers");

                    b.Navigation("Movements");

                    b.Navigation("OutgoingTransfers");
                });

            modelBuilder.Entity("CaioMatheusDev.Api.Infrastructure.Persistence.Entities.WalletTransferEntity", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
